ThrowRange:
  default: 1.0
  run: 1.5
  shift: 0.7
Bims:
  TimerBim:
      damage: 2.0
      price: 5
  CrackerBim:
      damage: 1.4
      price: 10
  FlameBim:
      damage: -1
      price: 15
  HomingBim:
      damage: 1.4
      speed: 2.0
      price: 20
  InstallationBim:
      damage: 2.5
      range: 2.0
      price: 30